### ISSUE TITLE
Inspirational websites

### ISSUE THREAD

**Issue by daniel-vera-g** [daniel-vera-g/daniel-vera-g.github.io#5]
Use Foam for also Blog posts: https://foambubble.github.io/foam/publishing/publish-to-github-pages

---

https://mydevportfol.io/ | MyDevPortfol.io
https://patrickcollison.com/about | About · Patrick Collison
https://www.youtube.com/watch?v=Eps1paAaLC8&index=13&list=WL | How to Create a Portfolio Website - YouTube
https://medium.freecodecamp.org/15-web-developer-portfolios-to-inspire-you-137fb1743cae | 15 Web Developer Portfolios to Inspire You – freeCodeCamp.org
https://github.com/afnanenayet/personal_blog | afnanenayet/personal_blog: My personal blog/website. Powered by Jekyll and Travis CI
https://github.com/maxpou/gatsby-starter-morning-dew | maxpou/gatsby-starter-morning-dew: a Gatsby v2 starter for blogs
https://writing.markchristian.org/2019/04/29/personal-web-sites/ | You should have a personal web site - ideas & ramblings
https://jrl.ninja/ | j
https://thesquareplanet.com/ | Jon Gjengset
https://karllorey.com/ | Karl Lorey: Founder, Investor, Techie — Karl Lorey
https://dev.to/ekafyi/building-my-personal-site--part-1-planning-and-designing-4fm | Building My Personal Site – Part 1: Planning and Designing - DEV Community 👩‍💻👨‍💻
https://patrickcollison.com/ | Home · Patrick Collison
http://adam3.us/ | Adam Back – Applied Cryptographer, Inventor Hashcash, Comp Sci PhD Distributed Systems
https://dev.to/emmawedekind/how-to-build-a-great-technical-portfolio-53bb?utm_source=Newsletter+Subscribers&utm_campaign=bd8f7b0ddf-EMAIL_CAMPAIGN_2019_01_14_07_51&utm_medium=email&utm_term=0_d8f11d5d1e-bd8f7b0ddf-154737769 | How To Build A Great Technical Portfolio - DEV Community 👩‍💻👨‍💻
http://justinmoon.com/ | Justin Moon
https://zen-of-programming.com/kickass-portfolio | The Zen of Programming

**Comment by lorey** [comment]
Nice to see me getting mentioned, my code is on github btw: https://github.com/lorey/karllorey.com
